name: Model

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover test/
      - name: Generate JSON schema
        run: python src/generate_schema.py mmft_model.json
      - uses: stefanzweifel/git-auto-commit-action@v5
        commit_message: Generate JSON schema
        file_pattern: ./mmft_model.json